on:
    push:
        branches:
        - main
        tags:
        - '!*'
    pull_request:
        branches:
        - main
 
name: main
jobs:
    test:
        name: Test on node
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
                os: [ubuntu-latest, macOS-latest, windows-latest]
            
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                 node-version: ${{ matrix.node-version }}

            - name: Create configuration.json for tests
              run: |
                  echo '{
                            "ambiente": "PRODUCAO", 
                            "idCorreios" : "${{ secrets.ID_CORREIOS }}", 
                            "codigoAcesso" :   "${{ secrets.CODIGO_ACESSO }}",
                            "contrato" : "${{ secrets.NUMERO_CONTRATO }}",
                            "cartaoPostagem": "${{ secrets.CARTAO_POSTAGEM }}"
                        }' > ./configuration.json
                        
            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  npm test 

